spring:
  data:
    elasticsearch:

      cluster-nodes: 192.168.3.49:9300
      # 节点名称，默认为elasticsearch，如果docker安装的，这里是docker-cluster
      # http://localhost:9200/_cluster/state 查看节点名称
      cluster-name: elasticsearch-cluster
      node:
        ingest: true
        repositories:
          enabled: true
server:
  port: 8033